name: featgg
description: "Official frontend application for Feat.gg. Powered by Flutter, Riverpod, and Supabase."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.10.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Backend
  supabase_flutter: 2.12.0

  # State management
  flutter_riverpod: 3.1.0
  riverpod_annotation: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: 6.0.0

  # Codegen
  build_runner: 2.10.5
  riverpod_generator: 4.0.0+1

flutter:
  uses-material-design: true
